<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFW0St2c\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFW0St2c/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFW0St2c.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFW0St2c\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFW0St2c\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'FW0St2c',
    'container.build_id' => 'cef67741',
    'container.build_time' => 1582290655,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFW0St2c');
