<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUxsz9Bh\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUxsz9Bh/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUxsz9Bh.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUxsz9Bh\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUxsz9Bh\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Uxsz9Bh',
    'container.build_id' => 'b2e72f23',
    'container.build_time' => 1582283618,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUxsz9Bh');
