<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJrtjEHc\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJrtjEHc/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJrtjEHc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJrtjEHc\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJrtjEHc\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'JrtjEHc',
    'container.build_id' => '304bbe93',
    'container.build_time' => 1582278455,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJrtjEHc');
